# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 20:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('contact_email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('slide_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='slides.Slide')),
                ('image', models.ImageField(upload_to='images')),
            ],
            bases=('slides.slide',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('slide_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='slides.Slide')),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
            ],
            bases=('slides.slide',),
        ),
    ]
