# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('contact_email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BioSlide',
            fields=[
                ('slide_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='slides.Slide')),
                ('image', models.ImageField(upload_to='images')),
            ],
            bases=('slides.slide',),
        ),
        migrations.CreateModel(
            name='CalendarSlide',
            fields=[
                ('slide_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='slides.Slide')),
            ],
            bases=('slides.slide',),
        ),
        migrations.CreateModel(
            name='EventSlide',
            fields=[
                ('slide_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='slides.Slide')),
                ('location', models.CharField(max_length=50)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.CalendarSlide')),
            ],
            bases=('slides.slide',),
        ),
        migrations.AddField(
            model_name='slide',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.Presentation'),
        ),
    ]
