# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('image', models.ImageField(upload_to='events')),
            ],
        ),
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('position', models.CharField(max_length=50)),
                ('contact_email', models.EmailField(max_length=50)),
                ('image', models.ImageField(upload_to='presenter')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='presenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slides.Presenter'),
        ),
    ]
